spring.application.name=Portfolio_investment
spring.datasource.url=jdbc:mysql://localhost:3306/trading_db
spring.datasource.username=root
spring.datasource.password=Aditya36@samal

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
alphavantage.api.key=TEEJX7Z8R6SOHC7M

spring.main.allow-bean-definition-overriding=true